### PR TITLE
FEATURE:  Hide hexadecimal forms #37

### PR DESCRIPTION
**Pull request by amhhernandez**
This is a proposal for the feature request #37.

In this pull request I added a `hideHexForm` flag so it can make a simpler view. Some times the final user doesn't need to know what hex color is being used by the component.

This is a screenshot of this proposal:

image

### CODE REVIEW

**Comment by amhhernandez** [comment]
There you go, the ng-container was added.

**Comment by amhhernandez** [comment]
Hi @tiaguinho any news on this PR? Is there anything I can do to fix/improve it? :) I'm happy to contribute.

Good day/night wherever you are :taco:

**Comment by tiaguinho** [comment]
Hi @amhhernandez.
This week has been crazy... I'll test the PR's tomorrow and merge into master.

Sorry for the delay.

**Comment by tiaguinho** [comment]
Hi @amhhernandez.
Can you implement an example of the usage in the demo app?

**Comment by amhhernandez** [comment]
Hey @tiaguinho 

Sure, I'll work on it, right now I'm packing my entire house, I'll move to another place so please be patient 😛

**Comment by amhhernandez** [comment]
@tiaguinho I had a very short chance to make the change you requested today early. The new feature has been added to the demo app, please give it an eye and tell me if there's anything else I can do to improve it, I'll be happy to fix it.

**Comment by amhhernandez** [comment]
hi @tiaguinho it's been two weeks, I know you're busy, just keep me up to date if anything is needed :)

Cheers! 🍺

**Comment by tiaguinho** [comment]
Hi, @amhhernandez the busy weeks are done, I'm returning to do the merges.
Everything looks fine, just please remove the ```.md``` files.

**Pull request merged**
