### PR TITLE
Angular 6 compatibility

### PR DESCRIPTION
**Pull request by DocLM**
Fix the code to work with Angular 6 upcoming release.

See #42

### CODE REVIEW

**Comment by tiaguinho** [comment]
This look's good.
But I think we can do this merge when the final version is released.

What do you think @DocLM?

**Comment by DocLM** [comment]
I agree. Maybe we can investigate if we can allow back-compatibility using rxjs-forward package.
In this version the angular/cli cannot serve the demo app because project structure is changed in Angular 6.
I tried @angular/cli beta-8 and rc.0 but they changed the structure another time so I will wait for an official release prior to migrate it with the cli.

**Comment by DocLM** [comment]
@tiaguinho I updated package.json with rxjs 5.6.0-forward-compat and it work. The package appear to work with both Angular 5 and 6.

**Comment by tiaguinho** [comment]
This is a good news @DocLM!
Now we can import everything from ```rxjs```, so I think you can change the imports for something like:

```typescript
import { Observable, Subscription } from 'rxjs';
```

Do you think this is valid?

**Comment by DocLM** [comment]
Exactly @tiaguinho. I clean up the code with single rxjs imports

**Comment by DocLM** [comment]
@tiaguinho Can you merge? Angular 6 was released today

**Comment by ranouf** [comment]
I have an error
import { BehaviorSubject } from 'rxjs';
[...]
  private _isAuthenticated: BehaviorSubject<boolean>;
[...]
    return this._isAuthenticated.distinctUntilChanged();

Error:
error TS2339: Property 'distinctUntilChanged' does not exist on type 'BehaviorSubject<boolean>'.

how to use distinctUntilChanged and other function of BehaviorSubject & Observable with the new updates?

**Comment by DocLM** [comment]
@ranouf Not related to mcc. You need to add this line

`import 'rxjs/add/operator/distinctUntilChanged';`

or use pipe operator

`import { distinctUntilChanged } from 'rxjs/operators';`

**Pull request merged**
