### PR TITLE
feat(color-picker, time-picker): round corners, @HostListeners, openOnFocus for mccColorPickerOrigin, examples, time picker fixes

### PR DESCRIPTION
**Pull request by motabass**
implements #148

### CODE REVIEW

**Comment by motabass** [comment]
This also removes open Sans font and uses Roboto instead, aligns border-radius and elevation with what **@angular/material** uses for the datepicker (z4, and border-radius: 4px)

**Comment by tiaguinho** [comment]
@motabass this is ready for review?

**Comment by motabass** [comment]
@tiaguinho yes

**Comment by motabass** [comment]
@tiaguinho i re-added the animation and the comment. I removed the @param comments because they seemed redundant to me when strongly typing it with TS.

**Comment by tiaguinho** [comment]
Makes sense @motabass. 
Let's remove the animation.

Thank you!

**Pull request merged**
